<?php

declare(strict_types=1);

namespace App\Support\Demo;

/**
 * A one-page PDF, written by hand as bytes.
 *
 * `cass:demo-seed` needs an attachment per abstract that survives
 * StoreSubmissionFile - which sniffs the content with finfo and demands
 * `application/pdf` (App\Support\Files\SniffedMimeType) - and the production
 * image installs no dev dependencies, so adding a PDF library for a demo
 * seeder would put it in every release for ever. A PDF is a list of numbered
 * objects, a cross-reference table of their byte offsets and a trailer; with
 * one of the fourteen standard Type1 fonts there is nothing to embed, so the
 * whole file is a few hundred bytes of ASCII.
 *
 * Deliberately minimal and deliberately not general: it draws a title, a
 * reference and two fixed lines saying what the file is. GenerateConferencePoster
 * remains the real PDF path in this codebase.
 */
final class DemoPdf
{
    /** A4 in PostScript points, which is what MediaBox is measured in. */
    private const WIDTH = 595;

    private const HEIGHT = 842;

    /**
     * @param  string  $title  the abstract's title, drawn at the top
     * @param  string  $reference  the abstract's reference, or a placeholder for a draft
     */
    public static function render(string $title, string $reference): string
    {
        $lines = [
            [self::HEIGHT - 70, 16, self::escape($title)],
            [self::HEIGHT - 100, 11, self::escape($reference)],
            [self::HEIGHT - 130, 11, self::escape('Demonstration data generated by cass:demo-seed.')],
            [self::HEIGHT - 148, 11, self::escape('No real patients, authors or institutions are named.')],
        ];

        $text = "BT\n";

        foreach ($lines as [$y, $size, $string]) {
            // Tm rather than Td, because Td is *relative* to the previous text
            // line and four stacked Td operators would each offset from the one
            // before - so the absolute y values above would compound into
            // negative coordinates and the last two lines would render off the
            // bottom of the page.
            $text .= "/F1 {$size} Tf\n1 0 0 1 56 {$y} Tm\n({$string}) Tj\n";
        }

        $text .= "ET\n";

        $objects = [
            '<< /Type /Catalog /Pages 2 0 R >>',
            '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
            '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 '.self::WIDTH.' '.self::HEIGHT.']'
                .' /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
            '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
            '<< /Length '.strlen($text)." >>\nstream\n".$text.'endstream',
        ];

        // finfo reads the header from the first bytes, so `%PDF-` has to be the
        // very first thing in the file. The binary comment on the second line is
        // what tells anything transferring the file to treat it as binary; it is
        // in every PDF a real producer writes.
        $pdf = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";

        $offsets = [];

        foreach ($objects as $index => $body) {
            $offsets[] = strlen($pdf);
            $number = $index + 1;
            $pdf .= "{$number} 0 obj\n{$body}\nendobj\n";
        }

        $startXref = strlen($pdf);
        $size = count($objects) + 1;

        // Each xref entry is exactly twenty bytes including the line ending,
        // which is why the trailing space after 'n' and 'f' matters.
        $pdf .= "xref\n0 {$size}\n0000000000 65535 f \n";

        foreach ($offsets as $offset) {
            $pdf .= str_pad((string) $offset, 10, '0', STR_PAD_LEFT)." 00000 n \n";
        }

        $pdf .= "trailer\n<< /Size {$size} /Root 1 0 R >>\nstartxref\n{$startXref}\n%%EOF\n";

        return $pdf;
    }

    /**
     * A PDF string literal is parenthesised, so a backslash, a bracket or a
     * newline inside it would end the string early and produce a file no reader
     * opens. Everything outside printable ASCII is dropped rather than encoded:
     * WinAnsiEncoding could carry Latin-1, but the demo content is English by
     * construction and a half-encoded byte is worse than a missing character.
     */
    private static function escape(string $value): string
    {
        $ascii = preg_replace('/[^\x20-\x7E]/', ' ', $value) ?? '';

        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $ascii);
    }
}
